"""analysis tables: snapshots, sentiment, scores, llm_calls

Revision ID: fff1c3e50161
Revises: 2e610281e49f
Create Date: 2026-06-11 20:06:47.385739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff1c3e50161'
down_revision: Union[str, Sequence[str], None] = '2e610281e49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_site', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_call_site'), 'llm_calls', ['call_site'], unique=False)
    op.create_table('indicator_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'date', name='uq_indicator_snapshots_instrument_date')
    )
    op.create_index(op.f('ix_indicator_snapshots_instrument_id'), 'indicator_snapshots', ['instrument_id'], unique=False)
    op.create_table('sentiment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_items_instrument_id'), 'sentiment_items', ['instrument_id'], unique=False)
    op.create_table('sentiment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'date', name='uq_sentiment_scores_instrument_date')
    )
    op.create_index(op.f('ix_sentiment_scores_instrument_id'), 'sentiment_scores', ['instrument_id'], unique=False)
    op.create_table('stock_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'date', name='uq_stock_scores_instrument_date')
    )
    op.create_index(op.f('ix_stock_scores_date'), 'stock_scores', ['date'], unique=False)
    op.create_index(op.f('ix_stock_scores_instrument_id'), 'stock_scores', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_scores_instrument_id'), table_name='stock_scores')
    op.drop_index(op.f('ix_stock_scores_date'), table_name='stock_scores')
    op.drop_table('stock_scores')
    op.drop_index(op.f('ix_sentiment_scores_instrument_id'), table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index(op.f('ix_sentiment_items_instrument_id'), table_name='sentiment_items')
    op.drop_table('sentiment_items')
    op.drop_index(op.f('ix_indicator_snapshots_instrument_id'), table_name='indicator_snapshots')
    op.drop_table('indicator_snapshots')
    op.drop_index(op.f('ix_llm_calls_call_site'), table_name='llm_calls')
    op.drop_table('llm_calls')
    # ### end Alembic commands ###
